version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 3s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"
  
  Measurement-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data_measurement_db:/var/opt/mssql

  Patient-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - mssql_data_patient_db:/var/opt/mssql

  measurementservice:
    build:
      context: .
      dockerfile: ./MeasurementService/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - Measurement-db

  patientservice:
    build:
      context: .
      dockerfile: ./PatientService/Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - Patient-db

  doctoruifrontend:
    ports:
      - "8070:80"
    build:
      context: .
      dockerfile: ./Frontend/angular-DoctorUI/Dockerfile
    volumes:
      - ./Frontend/angular-DoctorUI/src:/app/src:delegated
    depends_on:
      - measurementservice

  patientuifrontend:
    ports:
      - "8060:80"
    build:
      context: .
      dockerfile: ./Frontend/angular-PatientUI/Dockerfile
    volumes:
      - ./Frontend/angular-PatientUI/src:/app/src:delegated
    depends_on:
      - patientservice

volumes:
  mssql_data_patient_db:
  mssql_data_measurement_db: