version: '3.8'

services:
  Measurement-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  Patient-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"

  measurementservice:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - Measurement-db

  patientservice:
    build:
      context: .
      dockerfile: ./PatientService/Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - Patient-db

  doctoruifrontend:
    ports:
      - "8070:80"
    build:
      context: .
      dockerfile: ./Frontend/angular-DoctorUI/Dockerfile
    volumes:
      - ./Frontend/angular-DoctorUI/src:/app/src:delegated
    depends_on:
      - measurementservice

  patientuifrontend:
    ports:
      - "8060:80"
    build:
      context: .
      dockerfile: ./Frontend/angular-PatientUI/Dockerfile
    volumes:
      - ./Frontend/angular-PatientUI/src:/app/src:delegated
    depends_on:
      - patientservice


volumes:
  measurement-mssql-data:
  patient-mssql-data: