// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientInfrastructure;

#nullable disable

namespace PatientInfrastructure.Migrations
{
    [DbContext(typeof(RepositoryDBContext))]
    [Migration("20240429155322_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.PatientBE", b =>
                {
                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            SSN = "123",
                            Email = "Olaf@mail.com",
                            Name = "Olaf"
                        },
                        new
                        {
                            SSN = "1234",
                            Email = "Jens@mail.com",
                            Name = "Jens"
                        },
                        new
                        {
                            SSN = "12345",
                            Email = "Benny@mail.com",
                            Name = "Benny"
                        },
                        new
                        {
                            SSN = "123456",
                            Email = "Lars@mail.com",
                            Name = "Lars"
                        },
                        new
                        {
                            SSN = "1234567",
                            Email = "Vladimir@mail.com",
                            Name = "Vladimir"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
